services:
  # データベース（MySQL）
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tech_forge_development
      MYSQL_USER: tech_forge_user
      MYSQL_PASSWORD: tech_forge_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # キャッシュ（Redis）
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # バックエンドAPI（Rails）
  api:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://tech_forge_user:tech_forge_password@db:3306/tech_forge_development
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: development_secret_key_change_in_production
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      timeout: 10s
      retries: 5

  # フロントエンド（React）
  frontend:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: development
      VITE_API_URL: http://api:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

  # Webサーバー（Nginx）
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - api
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app/dist:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  redis_data:
  bundle_cache:
  node_modules: